project_id = "geovwgfbbfhhmommyasj"

[functions.send-finance-alert]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.create-sell-request]
verify_jwt = false

[functions.get-handover-data]
verify_jwt = false

[functions.upload-client-doc]
verify_jwt = false
